### ISSUE TITLE
`npm run dev` results in errors

### ISSUE THREAD

**Issue by TheDutchCoder** [adamwathan/tailwind-jit-vite-example#2]
Hey I tried cloning this repo to debug some Vite + Tailwind JIT stuff, but after an `npm i` it doesn't seem to work.

Here's the full output:
```
> jit-vite@0.0.0 dev /Users/reinierkaper/personal/tailwind-jit-vite-example
> vite

Pre-bundling dependencies:
  vue
(this will be run only when your dependencies or config have changed)
Port 3000 is in use, trying another one...

  vite v2.1.2 dev server running at:

  > Local:    http://localhost:3001/
  > Network:  http://192.168.1.58:3001/

  ready in 813ms.

[@vue/compiler-sfc] <script setup> is still an experimental proposal.
Follow its status at https://github.com/vuejs/rfcs/pull/227.

[@vue/compiler-sfc] When using experimental features,
it is recommended to pin your vue dependencies to exact versions to avoid breakage.

10:55:17 a.m. [vite] Internal server error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss/lib/lib/evaluateTailwindFunctions'
Require stack:
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/@tailwindcss/jit/src/index.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/cli.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/bin/vite.js

(@/Users/reinierkaper/personal/tailwind-jit-vite-example/postcss.config.js)
  Plugin: vite:css
  File: /Users/reinierkaper/personal/tailwind-jit-vite-example/src/tailwind.css
      at load$1 (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16098:11)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16123:16
      at Array.map (<anonymous>)
      at plugins (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16122:8)
      at processResult (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16187:14)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16248:14
      at async resolvePostcssConfig (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18942:39)
      at async compileCSS (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18801:27)
      at async TransformContext.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18523:50)
      at async Object.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:43649:30)
10:55:17 a.m. [vite] Internal server error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss/lib/lib/evaluateTailwindFunctions'
Require stack:
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/@tailwindcss/jit/src/index.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/cli.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/bin/vite.js

(@/Users/reinierkaper/personal/tailwind-jit-vite-example/postcss.config.js)
  Plugin: vite:css
  File: /Users/reinierkaper/personal/tailwind-jit-vite-example/src/App.vue?vue&type=style&index=0&scoped=true&lang.css
      at load$1 (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16098:11)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16123:16
      at Array.map (<anonymous>)
      at plugins (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16122:8)
      at processResult (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16187:14)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16248:14
      at async resolvePostcssConfig (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18942:39)
      at async compileCSS (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18801:27)
      at async TransformContext.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18523:50)
      at async Object.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:43649:30)
10:55:17 a.m. [vite] Internal server error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss/lib/lib/evaluateTailwindFunctions'
Require stack:
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/@tailwindcss/jit/src/index.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/cli.js
- /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/bin/vite.js

(@/Users/reinierkaper/personal/tailwind-jit-vite-example/postcss.config.js)
  Plugin: vite:css
  File: /Users/reinierkaper/personal/tailwind-jit-vite-example/src/components/HelloWorld.vue?vue&type=style&index=0&scoped=true&lang.css
      at load$1 (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16098:11)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16123:16
      at Array.map (<anonymous>)
      at plugins (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16122:8)
      at processResult (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16187:14)
      at /Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:16248:14
      at async resolvePostcssConfig (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18942:39)
      at async compileCSS (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18801:27)
      at async TransformContext.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:18523:50)
      at async Object.transform (/Users/reinierkaper/personal/tailwind-jit-vite-example/node_modules/vite/dist/node/chunks/dep-efe32886.js:43649:30)
```

**Comment by adamwathan** [comment]
Yeah I don’t even remember what I created this repo for but you need to add postcss and tailwindcss as explicit dependencies, that’s what the error is telling you.

**Comment by TheDutchCoder** [comment]
Ah yes, that makes sense
